GET http://localhost:3000/api/v1/tours

###
POST http://localhost:3000/api/v1/tours
Content-Type: application/json

{
    "name": "test",
    "duration": 10,
    "difficulty": "easdy",
    "price": 20
}

###
PATCH  http://localhost:3000/api/v1/tours/6
Content-Type: application/json

{
    "name": "tet",
    "difficulty": "easy"
}

###
DELETE  http://localhost:3000/api/v1/tours/10


###
DELETE  http://localhost:3000/api/v1/users/1